### ISSUE TITLE
Fix Broken Navigation Links in Documentation and Main Site

### ISSUE THREAD

**Issue by akuya-ekorot** [mastra-ai/mastra#1100]
## Description

Multiple navigation links on the documentation site's landing page and main website pointing to the documentation are currently broken.

## Details

- Broken links on the main website:
  - Docs button on the `Assemble Agents` section
  - Docs and Example buttons on the `Build a Knowledge Base` section
- Broken links on the documentation site:
  - The table showcasing features has all links broken except for the `LLM Models` and `Evals` links.

## Steps to Reproduce

1. Visit the main website and documentation
2. Attempt to navigate to the specified sections listed above
3. Observe 404 errors or incorrect routing

## Expected Behavior

All navigation links should direct users to their intended destination

**Comment by akuya-ekorot** [comment]
Hi team. Mastra is looking great and cannot wait to jump into using the project. While taking a first glance at the resources provided, I found the following issues as listed in the description above.

I'd like to contribute to the project and help fix them. May I proceed with working on these?

**Comment by Joshuafolorunsho** [comment]
Thanks for catching that @akuya-ekorot.
The docs has been changing real fast.
You might not be able to fix the broken links on the website because it's not open source.

**Comment by Joshuafolorunsho** [comment]
Wasn't sure when you'll see this or when you'll make a PR to fix.
That's why I made a PR to close this. That said, you're fully welcome to contribute.
