### ISSUE TITLE
Support for other vector stores?

### ISSUE THREAD

**Issue by philnash** [mastra-ai/mastra#788]
Hello,

Love the look of the project! I was wondering whether you were interested in pull requests for other vector stores? Or whether that is better handled through plugins or some other system?

I'd be very happy to write one for [Astra DB](https://docs.datastax.com/en/astra-db-serverless/get-started/astra-db-introduction.html) for a start. Just want to know the best way to contribute to the project.

Thanks!

**Comment by calcsam** [comment]
We would love that! We will be shipping a couple other vector stores in the next week or two -- would be great to get Astra support as well. If you PR an `astra` folder into [this directory](https://github.com/mastra-ai/mastra/tree/main/packages/rag/src) we will review the PR! 

You can look at the Pinecone and pgvector integrations for the main APIs to implement: `query`, `createIndex` etc.

**Comment by philnash** [comment]
Awesome, thanks @calcsam. Will get on that.

**Comment by abhiaiyer91** [comment]
I'm going to close this ticket as we do support other vector stores and welcome PRs. We will get that AstraDB PR merged as soon as possible
