### ISSUE TITLE
Support OpenRouter

### ISSUE THREAD

**Issue by austinm911** [mastra-ai/mastra#851]
[Frameworks | OpenRouter](https://openrouter.ai/docs/frameworks)

This would enable more model options.

Could use the OpenAI SDK or their Vercel AI SDK integration (or both in case user needs to switch in case the underlying model doesn't work as expected with one or the other SDK or just user's preference to stick with one SDK over another).

**Comment by abhiaiyer91** [comment]
We support passing in your own models like the portkey example below

```
const portkeyConfig = {
  provider: 'openai', //enter provider of choice
  api_key: process.env.OPENAI_API_KEY, //enter the respective provider's api key
  override_params: {
    model: 'gpt-4', //choose from 250+ LLMs
  },
};

const portkey = createPortkey({
  apiKey: process.env.PORTKEY_API_KEY,
  config: portkeyConfig,
});

const chatModel = portkey.chatModel('');
export const agent = new Agent<typeof tools, typeof integrations>({
  name: 'Agent',
  instructions: 'Do this',
  model: {
    model: chatModel,
    provider: 'Portkey',
    toolChoice: 'required',
  },
});
```

So similarly you can use 

```
const openrouter = createOpenRouter({
    apiKey: process.env.OPENROUTER_API_KEY,
  });


export const agent = new Agent<typeof tools, typeof integrations>({
  name: 'Agent',
  instructions: 'Do this',
  model: {
    model: openRouter(modelName),
    provider: 'MODEL_NAME',
    toolChoice: 'required',
  },
});
```

**Comment by austinm911** [comment]
> We support passing in your own models like the portkey example below
> 
> ```
> const portkeyConfig = {
>   provider: 'openai', //enter provider of choice
>   api_key: process.env.OPENAI_API_KEY, //enter the respective provider's api key
>   override_params: {
>     model: 'gpt-4', //choose from 250+ LLMs
>   },
> };
> 
> const portkey = createPortkey({
>   apiKey: process.env.PORTKEY_API_KEY,
>   config: portkeyConfig,
> });
> 
> const chatModel = portkey.chatModel('');
> export const agent = new Agent<typeof tools, typeof integrations>({
>   name: 'Agent',
>   instructions: 'Do this',
>   model: {
>     model: chatModel,
>     provider: 'Portkey',
>     toolChoice: 'required',
>   },
> });
> ```
> 
> So similarly you can use
> 
> ```
> const openrouter = createOpenRouter({
>     apiKey: process.env.OPENROUTER_API_KEY,
>   });
> 
> 
> export const agent = new Agent<typeof tools, typeof integrations>({
>   name: 'Agent',
>   instructions: 'Do this',
>   model: {
>     model: openRouter(modelName),
>     provider: 'MODEL_NAME',
>     toolChoice: 'required',
>   },
> });
> ```

Oh great - missed this from the docs, thank you!

**Comment by puneetv05** [comment]
It seems the API has changed recently; this doesn't work anymore, trying the weather example:

**agent code:**
```
import { Agent } from "@mastra/core/agent";
import { weatherTool } from "../tools";
import { createOpenRouter } from "@openrouter/ai-sdk-provider";

const openrouter = createOpenRouter({
  apiKey: process.env.OPENROUTER_API_KEY,
});

// const model = openrouter.chat("deepseek/deepseek-r1:free");
export const weatherAgent = new Agent({
  name: "Weather Agent",
  instructions: `
      You are a helpful weather assistant that provides accurate weather information.

      Your primary function is to help users get weather details for specific locations. When responding:
      - Always ask for a location if none is provided
      - If giving a location with multiple parts (e.g. "New York, NY"), use the most relevant part (e.g. "New York")
      - Include relevant details like humidity, wind conditions, and precipitation
      - Keep responses concise but informative

      Use the weatherTool to fetch current weather data.
`,
  model: openrouter("deepseek/deepseek-r1:free"),
  tools: { weatherTool },
});
```
here are screenshots, lmk i can provide more logs or info :

<img width="915" alt="Image" src="https://github.com/user-attachments/assets/39d19cf6-8a72-4db8-8ec2-f5680d5df861" />

<img width="741" alt="Image" src="https://github.com/user-attachments/assets/c3e857c6-4706-4ccc-9ae2-92dd113950a4" />
